// AUTO-GENERATED by scripts/sync-shared-code.cjs. Do not edit directly.

import { Unyuck } from '@technomoron/unyuck';

export type FlattenedAsset = {
	filename: string;
	path: string;
	cid?: string;
};

export type FlattenWithAssetsOptions = {
	domainRoot: string;
	templateKey: string;
	baseUrl: string;
	assetFormatter: (urlPath: string) => string;
	normalizeInlineCid?: (urlPath: string) => string;
};

export type FlattenWithAssetsResult = {
	html: string;
	assets: FlattenedAsset[];
};

function defaultInlineAssetCid(urlPath: string): string {
	const normalized = String(urlPath || '')
		.trim()
		.replace(/\\/g, '/');
	const safe = normalized.replace(/[^A-Za-z0-9._-]/g, '_').replace(/_+/g, '_');
	return (safe || 'asset').slice(0, 200);
}

export function flattenTemplateWithAssets(options: FlattenWithAssetsOptions): FlattenWithAssetsResult {
	const processor = new Unyuck({
		basePath: options.domainRoot,
		baseUrl: options.baseUrl,
		collectAssets: true,
		assetFormatter: (ctx: { urlPath: string }) => options.assetFormatter(ctx.urlPath)
	});
	const { html: mergedHtml, assets } = processor.flattenWithAssets(options.templateKey);
	let html = mergedHtml;

	const normalizeCid = options.normalizeInlineCid ?? defaultInlineAssetCid;

	const mappedAssets: FlattenedAsset[] = assets.map((asset: { filename: string; path: string; cid?: string }) => {
		const rel = asset.filename.replace(/\\/g, '/');
		const urlPath = rel.startsWith('assets/') ? rel.slice('assets/'.length) : rel;
		return {
			filename: urlPath,
			path: asset.path,
			cid: asset.cid ? normalizeCid(urlPath) : undefined
		};
	});

	for (const asset of assets) {
		if (!asset.cid) {
			continue;
		}
		const rel = asset.filename.replace(/\\/g, '/');
		const urlPath = rel.startsWith('assets/') ? rel.slice('assets/'.length) : rel;
		const desiredCid = normalizeCid(urlPath);
		if (asset.cid !== desiredCid) {
			html = html.split(`cid:${asset.cid}`).join(`cid:${desiredCid}`);
		}
	}

	return { html, assets: mappedAssets };
}
